language: go
go:
 - 1.13
before_script:
  - go vet ./...
script:
  - go test -v ./...
  - go test -race -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)
